name: Example
options:
  bundleIdPrefix: dev.declarativeappkit
  deploymentTarget:
    macOS: "12.0"
  developmentLanguage: en
packages:
  DeclarativeAppKit:
    path: ..
targets:
  Example:
    type: application
    platform: macOS
    sources:
      - Example
    dependencies:
      - package: DeclarativeAppKit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        INFOPLIST_KEY_CFBundleDisplayName: DeclarativeAppKit Example
        PRODUCT_BUNDLE_IDENTIFIER: dev.declarativeappkit.Example
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
schemes:
  Example:
    build:
      targets:
        Example: all
    run:
      config: Debug
    archive:
      config: Release
